insert into public.categories (id, slug, name, short_name, description, category_group) values
  ('cat-emerging', 'emerging', 'Emerging Entrepreneur of the Year', 'Emerging Entrepreneur',
   'For the early-stage founder moving with the clarity and momentum of a venture twice its age.', 'A'),
  ('cat-beauty', 'beauty', 'Beauty & Makeup Entrepreneur of the Year', 'Beauty & Makeup',
   'Honouring the artistry and enterprise powering Lagos'' beauty economy.', 'A'),
  ('cat-import-export', 'import-export', 'Import & Export Entrepreneur of the Year', 'Import & Export',
   'For the traders connecting Lagos to global markets, in both directions.', 'A'),
  ('cat-tourism', 'tourism', 'Leisure, Tourism & Travel Entrepreneur of the Year', 'Leisure, Tourism & Travel',
   'For the operators selling the experience of Lagos, and the journeys that begin here.', 'A'),
  ('cat-real-estate', 'real-estate', 'Real Estate & Property Development Entrepreneur of the Year', 'Real Estate & Property',
   'Recognising the developers reshaping the Lagos skyline, plot by plot.', 'A'),
  ('cat-oil-gas', 'oil-gas', 'Oil & Gas Entrepreneur of the Year', 'Oil & Gas',
   'For young leaders building enterprise across the energy value chain.', 'A'),
  ('cat-security', 'security', 'Security Services Entrepreneur of the Year', 'Security Services',
   'Honouring the founders keeping people, assets and businesses protected.', 'A'),
  ('cat-energy', 'energy', 'Power & Renewable Energy Entrepreneur of the Year', 'Power & Renewable Energy',
   'For the innovators bringing reliable, cleaner power to homes and businesses.', 'A'),
  ('cat-fashion', 'fashion', 'Fashion & Style Entrepreneur of the Year', 'Fashion & Style',
   'For the ateliers and labels dressing a city the continent watches for cues.', 'A'),
  ('cat-social-impact', 'social-impact', 'Social Impact Entrepreneur of the Year', 'Social Impact',
   'For enterprise built to move communities forward, not just balance sheets.', 'A'),
  ('cat-teen', 'teen', 'Teen Entrepreneur of the Year', 'Teen Entrepreneur',
   'For the under-twenty founder already building with conviction.', 'A'),
  ('cat-hospitality', 'hospitality', 'Hotel & Hospitality Entrepreneur of the Year', 'Hotel & Hospitality',
   'Honouring the hosts who define how Lagos welcomes the world.', 'A'),
  ('cat-digital', 'digital', 'Online / Digital Entrepreneur of the Year', 'Online & Digital',
   'For ventures built for the screen-first economy and scaling fast.', 'A'),
  ('cat-entertainment', 'entertainment', 'Emerging Entertainment Entrepreneur of the Year', 'Emerging Entertainment',
   'For the promoters and producers scoring the soundtrack of a city that never sleeps.', 'A'),
  ('cat-chef', 'chef', 'Food (Chef & Grills) Entrepreneur of the Year', 'Food, Chef & Grills',
   'For the chefs and grill masters turning craft and flavour into thriving kitchens.', 'A'),
  ('cat-sports', 'sports', 'Sports Entrepreneur of the Year', 'Sports',
   'Honouring the founders building enterprise around sport, fitness and talent.', 'A'),
  ('cat-logistics', 'logistics', 'Logistics & Transportation Entrepreneur of the Year', 'Logistics & Transportation',
   'For the operators keeping a city of millions, and everything it buys, in motion.', 'A'),
  ('cat-female', 'female', 'Female Entrepreneur of the Year', 'Female Entrepreneur',
   'Celebrating the woman whose enterprise and leadership set the standard.', 'A'),
  ('cat-agribusiness', 'agribusiness', 'Agribusiness Entrepreneur of the Year', 'Agribusiness',
   'For the growers and processors feeding a megacity and farming its future.', 'A'),
  ('cat-tech', 'tech', 'ICT / Tech Startup Entrepreneur of the Year', 'ICT & Tech Startup',
   'For the technologists building the software and platforms Lagos runs on.', 'A'),
  ('cat-professional', 'professional', 'Professional Services Entrepreneur of the Year', 'Professional Services',
   'Medical, legal, finance and engineering practices built on rigour and trust.', 'A'),
  ('cat-student', 'student', 'Student Entrepreneur of the Year', 'Student Entrepreneur',
   'For the undergraduate balancing lecture halls and ledgers.', 'A'),
  ('cat-food-beverage', 'food-beverage', 'Food & Beverage Entrepreneur of the Year', 'Food & Beverage',
   'For the brands and businesses feeding Lagos at scale.', 'A'),
  ('cat-automobile', 'automobile', 'Automobile Entrepreneur of the Year', 'Automobile',
   'Honouring the dealers, builders and innovators of the auto economy.', 'A'),
  ('cat-blogger', 'blogger', 'Blogger of the Year', 'Blogger of the Year',
   'For the voice shaping the conversation and building a business around it.', 'A'),
  ('cat-interior', 'interior', 'Interior Design & Décor Entrepreneur of the Year', 'Interior Design & Décor',
   'For the designers turning rooms into experiences across Lagos.', 'A'),
  ('cat-fitness', 'fitness', 'Fitness & Wellness Entrepreneur of the Year', 'Fitness & Wellness',
   'For the founders building healthier bodies and a healthier city.', 'A'),
  ('cat-businesswoman', 'businesswoman', 'Outstanding Businesswoman of the Year', 'Outstanding Businesswoman',
   'For the businesswoman whose record speaks before she does.', 'A'),
  ('cat-disability', 'disability', 'Entrepreneur with Disability of the Year', 'Entrepreneur with Disability',
   'Honouring the founder building boldly, on their own terms.', 'A'),
  ('cat-influential', 'influential', 'Most Influential Young Entrepreneur of the Year', 'Most Influential Young Entrepreneur',
   'For the young founder whose reach moves markets and minds.', 'A'),
  ('cat-media', 'media', 'Media Entrepreneur of the Year', 'Media Entrepreneur',
   'For the founders building the platforms that inform and entertain Lagos.', 'A'),
  ('cat-events', 'events', 'Events Planning Entrepreneur of the Year', 'Events Planning',
   'For the planners who turn a date on a calendar into an unforgettable moment.', 'A'),
  ('cat-nightlife', 'nightlife', 'Nightlife Entrepreneur of the Year', 'Nightlife',
   'For the founders behind the lounges and rooms where Lagos comes alive after dark.', 'A'),
  ('cat-co-founder', 'co-founder', 'Co-Founder of the Year', 'Co-Founder of the Year',
   'For the partner whose contribution is half the reason a venture works.', 'A'),
  ('cat-ceo', 'ceo', 'CEO of the Year', 'CEO of the Year',
   'For the chief executive whose leadership turned strategy into results.', 'A'),
  ('cat-creative', 'creative', 'Content & Creative Entrepreneur of the Year', 'Content & Creative',
   'Honouring the storytellers turning craft into a thriving creative business.', 'A'),
  ('cat-talent', 'talent', 'Talent Promotion Entrepreneur of the Year', 'Talent Promotion',
   'For the managers and promoters building the careers behind the spotlight.', 'A'),
  ('cat-agrotourism', 'agrotourism', 'Agrotourism Entrepreneur of the Year', 'Agrotourism',
   'For the founders where agriculture meets experience and destination.', 'A'),
  ('cat-intrapreneur', 'intrapreneur', 'Intrapreneur of the Year Award', 'Intrapreneur of the Year',
   'For the in-house innovator building like a founder inside an organisation.', 'A'),
  ('cat-infrastructure', 'infrastructure', 'Infrastructure Development Entrepreneur of the Year', 'Infrastructure Development',
   'For the builders laying the physical foundations of a growing Lagos.', 'A'),

  ('cat-corporate-brand', 'corporate-brand', 'Corporate Brand Recognition Award', 'Corporate Brand Recognition',
   'Conferred on a corporate organisation whose work has measurably advanced enterprise in Lagos.', 'B'),
  ('cat-ngo', 'ngo', 'NGO of the Year Award', 'NGO of the Year',
   'Honouring a non-profit whose impact on Lagos communities stands above the rest.', 'B'),
  ('cat-lifetime', 'lifetime', 'Lifetime Entrepreneurship Achievement Award', 'Lifetime Achievement',
   'The evening''s highest honour, invested upon five business icons who have shaped the economic landscape.', 'B')
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  short_name = excluded.short_name,
  description = excluded.description,
  category_group = excluded.category_group;

